# Generated by Django 3.1.4 on 2020-12-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alterfield_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto')),
            ],
        ),
    ]
